/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Command model module.
 * @module model/Command
 * @version 0.0.0
 */
class Command {
    /**
     * Constructs a new <code>Command</code>.
     * Command represents a single command to execute by the Worker.
     * @alias module:model/Command
     * @param name {String} 
     * @param parameters {Object} 
     */
    constructor(name, parameters) { 
        
        Command.initialize(this, name, parameters);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, parameters) { 
        obj['name'] = name;
        obj['parameters'] = parameters;
    }

    /**
     * Constructs a <code>Command</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Command} obj Optional instance to populate.
     * @return {module:model/Command} The populated <code>Command</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Command();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Command.prototype['name'] = undefined;

/**
 * @member {Object} parameters
 */
Command.prototype['parameters'] = undefined;






export default Command;

