/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobStatus from './JobStatus';

/**
 * The JobUpdate model module.
 * @module model/JobUpdate
 * @version 0.0.0
 */
class JobUpdate {
    /**
     * Constructs a new <code>JobUpdate</code>.
     * @alias module:model/JobUpdate
     * @param id {String} UUID of the Job
     * @param updated {Date} Timestamp of last update
     * @param status {module:model/JobStatus} 
     */
    constructor(id, updated, status) { 
        
        JobUpdate.initialize(this, id, updated, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, updated, status) { 
        obj['id'] = id;
        obj['updated'] = updated;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>JobUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobUpdate} obj Optional instance to populate.
     * @return {module:model/JobUpdate} The populated <code>JobUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobUpdate();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = JobStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('previous_status')) {
                obj['previous_status'] = JobStatus.constructFromObject(data['previous_status']);
            }
        }
        return obj;
    }


}

/**
 * UUID of the Job
 * @member {String} id
 */
JobUpdate.prototype['id'] = undefined;

/**
 * Name of the job
 * @member {String} name
 */
JobUpdate.prototype['name'] = undefined;

/**
 * Timestamp of last update
 * @member {Date} updated
 */
JobUpdate.prototype['updated'] = undefined;

/**
 * @member {module:model/JobStatus} status
 */
JobUpdate.prototype['status'] = undefined;

/**
 * @member {module:model/JobStatus} previous_status
 */
JobUpdate.prototype['previous_status'] = undefined;






export default JobUpdate;

