/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ShamanFileStatus.
* @enum {}
* @readonly
*/
export default class ShamanFileStatus {
    
        /**
         * value: "unknown"
         * @const
         */
        "unknown" = "unknown";

    
        /**
         * value: "uploading"
         * @const
         */
        "uploading" = "uploading";

    
        /**
         * value: "stored"
         * @const
         */
        "stored" = "stored";

    

    /**
    * Returns a <code>ShamanFileStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ShamanFileStatus} The enum <code>ShamanFileStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

