/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ShamanFileStatus from './ShamanFileStatus';

/**
 * The ShamanSingleFileStatus model module.
 * @module model/ShamanSingleFileStatus
 * @version 0.0.0
 */
class ShamanSingleFileStatus {
    /**
     * Constructs a new <code>ShamanSingleFileStatus</code>.
     * Status of a file in the Shaman storage.
     * @alias module:model/ShamanSingleFileStatus
     * @param status {module:model/ShamanFileStatus} 
     */
    constructor(status) { 
        
        ShamanSingleFileStatus.initialize(this, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status) { 
        obj['status'] = status;
    }

    /**
     * Constructs a <code>ShamanSingleFileStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShamanSingleFileStatus} obj Optional instance to populate.
     * @return {module:model/ShamanSingleFileStatus} The populated <code>ShamanSingleFileStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShamanSingleFileStatus();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ShamanFileStatus.constructFromObject(data['status']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ShamanFileStatus} status
 */
ShamanSingleFileStatus.prototype['status'] = undefined;






export default ShamanSingleFileStatus;

