/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ShamanFileSpec model module.
 * @module model/ShamanFileSpec
 * @version 0.0.0
 */
class ShamanFileSpec {
    /**
     * Constructs a new <code>ShamanFileSpec</code>.
     * Specification of a file in the Shaman storage.
     * @alias module:model/ShamanFileSpec
     * @param sha {String} SHA256 checksum of the file
     * @param size {Number} File size in bytes
     * @param path {String} Location of the file in the checkout
     */
    constructor(sha, size, path) { 
        
        ShamanFileSpec.initialize(this, sha, size, path);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sha, size, path) { 
        obj['sha'] = sha;
        obj['size'] = size;
        obj['path'] = path;
    }

    /**
     * Constructs a <code>ShamanFileSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShamanFileSpec} obj Optional instance to populate.
     * @return {module:model/ShamanFileSpec} The populated <code>ShamanFileSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShamanFileSpec();

            if (data.hasOwnProperty('sha')) {
                obj['sha'] = ApiClient.convertToType(data['sha'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
        }
        return obj;
    }


}

/**
 * SHA256 checksum of the file
 * @member {String} sha
 */
ShamanFileSpec.prototype['sha'] = undefined;

/**
 * File size in bytes
 * @member {Number} size
 */
ShamanFileSpec.prototype['size'] = undefined;

/**
 * Location of the file in the checkout
 * @member {String} path
 */
ShamanFileSpec.prototype['path'] = undefined;






export default ShamanFileSpec;

