"""
    Flamenco manager

    Render Farm manager API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flamenco.manager
from flamenco.manager.model.worker_status import WorkerStatus
globals()['WorkerStatus'] = WorkerStatus
from flamenco.manager.model.worker_state_changed import WorkerStateChanged


class TestWorkerStateChanged(unittest.TestCase):
    """WorkerStateChanged unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkerStateChanged(self):
        """Test WorkerStateChanged"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkerStateChanged()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
