"""
    Flamenco manager

    Render Farm manager API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import flamenco.manager
from flamenco.manager.api.worker_api import WorkerApi  # noqa: E501


class TestWorkerApi(unittest.TestCase):
    """WorkerApi unit test stubs"""

    def setUp(self):
        self.api = WorkerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_register_worker(self):
        """Test case for register_worker

        Register a new worker  # noqa: E501
        """
        pass

    def test_schedule_task(self):
        """Test case for schedule_task

        Obtain a new task to execute  # noqa: E501
        """
        pass

    def test_sign_off(self):
        """Test case for sign_off

        Mark the worker as offline  # noqa: E501
        """
        pass

    def test_sign_on(self):
        """Test case for sign_on

        Authenticate & sign in the worker.  # noqa: E501
        """
        pass

    def test_task_update(self):
        """Test case for task_update

        Update the task, typically to indicate progress, completion, or failure.  # noqa: E501
        """
        pass

    def test_worker_state(self):
        """Test case for worker_state

        """
        pass

    def test_worker_state_changed(self):
        """Test case for worker_state_changed

        Worker changed state. This could be as acknowledgement of a Manager-requested state change, or in response to worker-local signals.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
