"""
    Flamenco manager

    Render Farm manager API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flamenco.manager
from flamenco.manager.model.job_status import JobStatus
globals()['JobStatus'] = JobStatus
from flamenco.manager.model.job_all_of import JobAllOf


class TestJobAllOf(unittest.TestCase):
    """JobAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobAllOf(self):
        """Test JobAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
