"""
    Flamenco manager

    Render Farm manager API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flamenco.manager
from flamenco.manager.model.worker_status import WorkerStatus


class TestWorkerStatus(unittest.TestCase):
    """WorkerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkerStatus(self):
        """Test WorkerStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkerStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
