"""
    Flamenco manager

    Render Farm manager API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flamenco.manager
from flamenco.manager.model.worker_status import WorkerStatus
globals()['WorkerStatus'] = WorkerStatus
from flamenco.manager.model.worker_state_change import WorkerStateChange


class TestWorkerStateChange(unittest.TestCase):
    """WorkerStateChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkerStateChange(self):
        """Test WorkerStateChange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkerStateChange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
