"""
    Flamenco manager

    Render Farm manager API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flamenco.manager
from flamenco.manager.model.configuration_meta import ConfigurationMeta
globals()['ConfigurationMeta'] = ConfigurationMeta
from flamenco.manager.model.configuration import Configuration


class TestConfiguration(unittest.TestCase):
    """Configuration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfiguration(self):
        """Test Configuration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Configuration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
