"""
    Flamenco manager

    Render Farm manager API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import flamenco.manager
from flamenco.manager.model.available_job_setting_subtype import AvailableJobSettingSubtype
from flamenco.manager.model.available_job_setting_type import AvailableJobSettingType
globals()['AvailableJobSettingSubtype'] = AvailableJobSettingSubtype
globals()['AvailableJobSettingType'] = AvailableJobSettingType
from flamenco.manager.model.available_job_setting import AvailableJobSetting


class TestAvailableJobSetting(unittest.TestCase):
    """AvailableJobSetting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailableJobSetting(self):
        """Test AvailableJobSetting"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AvailableJobSetting()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
