// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package api

const (
	Worker_authScopes = "worker_auth.Scopes"
)

// Defines values for TaskStatus.
const (
	TaskStatusActive TaskStatus = "active"

	TaskStatusCancelRequested TaskStatus = "cancel-requested"

	TaskStatusCanceled TaskStatus = "canceled"

	TaskStatusCompleted TaskStatus = "completed"

	TaskStatusFailRequested TaskStatus = "fail-requested"

	TaskStatusFailed TaskStatus = "failed"

	TaskStatusPaused TaskStatus = "paused"

	TaskStatusProcessing TaskStatus = "processing"

	TaskStatusQueued TaskStatus = "queued"

	TaskStatusSoftFailed TaskStatus = "soft-failed"
)

// AssignedTask is a task as it is received by the Worker.
type AssignedTask struct {
	Id          string     `json:"_id"`
	Commands    []Command  `json:"commands"`
	Job         string     `json:"job"`
	JobPriority int        `json:"job_priority"`
	JobType     string     `json:"job_type"`
	Name        string     `json:"name"`
	Priority    int        `json:"priority"`
	Status      TaskStatus `json:"status"`
	TaskType    string     `json:"task_type"`
	User        string     `json:"user"`
}

// Command represents a single command to execute by the Worker.
type Command struct {
	Name     string                 `json:"name"`
	Settings map[string]interface{} `json:"settings"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// RegisteredWorker defines model for RegisteredWorker.
type RegisteredWorker struct {
	Id                 string   `json:"_id"`
	Address            string   `json:"address"`
	LastActivity       string   `json:"last_activity"`
	Nickname           string   `json:"nickname"`
	Platform           string   `json:"platform"`
	Software           string   `json:"software"`
	Status             string   `json:"status"`
	SupportedTaskTypes []string `json:"supported_task_types"`
}

// SecurityError defines model for SecurityError.
type SecurityError struct {
	Message string `json:"message"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// WorkerRegistration defines model for WorkerRegistration.
type WorkerRegistration struct {
	Nickname           string   `json:"nickname"`
	Platform           string   `json:"platform"`
	Secret             string   `json:"secret"`
	SupportedTaskTypes []string `json:"supported_task_types"`
}

// RegisterWorkerJSONBody defines parameters for RegisterWorker.
type RegisterWorkerJSONBody WorkerRegistration

// RegisterWorkerJSONRequestBody defines body for RegisterWorker for application/json ContentType.
type RegisterWorkerJSONRequestBody RegisterWorkerJSONBody
