/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AvailableJobSettingVisibility.
* @enum {}
* @readonly
*/
export default class AvailableJobSettingVisibility {
    
        /**
         * value: "visible"
         * @const
         */
        "visible" = "visible";

    
        /**
         * value: "hidden"
         * @const
         */
        "hidden" = "hidden";

    
        /**
         * value: "submission"
         * @const
         */
        "submission" = "submission";

    
        /**
         * value: "web"
         * @const
         */
        "web" = "web";

    

    /**
    * Returns a <code>AvailableJobSettingVisibility</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AvailableJobSettingVisibility} The enum <code>AvailableJobSettingVisibility</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

