/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class JobStatus.
* @enum {}
* @readonly
*/
export default class JobStatus {
    
        /**
         * value: "active"
         * @const
         */
        "active" = "active";

    
        /**
         * value: "canceled"
         * @const
         */
        "canceled" = "canceled";

    
        /**
         * value: "completed"
         * @const
         */
        "completed" = "completed";

    
        /**
         * value: "construction-failed"
         * @const
         */
        "construction-failed" = "construction-failed";

    
        /**
         * value: "failed"
         * @const
         */
        "failed" = "failed";

    
        /**
         * value: "paused"
         * @const
         */
        "paused" = "paused";

    
        /**
         * value: "queued"
         * @const
         */
        "queued" = "queued";

    
        /**
         * value: "archived"
         * @const
         */
        "archived" = "archived";

    
        /**
         * value: "archiving"
         * @const
         */
        "archiving" = "archiving";

    
        /**
         * value: "cancel-requested"
         * @const
         */
        "cancel-requested" = "cancel-requested";

    
        /**
         * value: "requeueing"
         * @const
         */
        "requeueing" = "requeueing";

    
        /**
         * value: "under-construction"
         * @const
         */
        "under-construction" = "under-construction";

    

    /**
    * Returns a <code>JobStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/JobStatus} The enum <code>JobStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

