/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TaskStatus.
* @enum {}
* @readonly
*/
export default class TaskStatus {
    
        /**
         * value: "active"
         * @const
         */
        "active" = "active";

    
        /**
         * value: "canceled"
         * @const
         */
        "canceled" = "canceled";

    
        /**
         * value: "completed"
         * @const
         */
        "completed" = "completed";

    
        /**
         * value: "failed"
         * @const
         */
        "failed" = "failed";

    
        /**
         * value: "queued"
         * @const
         */
        "queued" = "queued";

    
        /**
         * value: "soft-failed"
         * @const
         */
        "soft-failed" = "soft-failed";

    
        /**
         * value: "paused"
         * @const
         */
        "paused" = "paused";

    

    /**
    * Returns a <code>TaskStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TaskStatus} The enum <code>TaskStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

