/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TaskStatus from './TaskStatus';

/**
 * The TaskUpdate model module.
 * @module model/TaskUpdate
 * @version 0.0.0
 */
class TaskUpdate {
    /**
     * Constructs a new <code>TaskUpdate</code>.
     * TaskUpdate is sent by a Worker to update the status &amp; logs of a task it&#39;s executing. All properties are optional; omitted properties are ignored (i.e. omitting &#x60;activity&#x60; will not erase the activity property of the task). 
     * @alias module:model/TaskUpdate
     */
    constructor() { 
        
        TaskUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TaskUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TaskUpdate} obj Optional instance to populate.
     * @return {module:model/TaskUpdate} The populated <code>TaskUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaskUpdate();

            if (data.hasOwnProperty('taskStatus')) {
                obj['taskStatus'] = TaskStatus.constructFromObject(data['taskStatus']);
            }
            if (data.hasOwnProperty('activity')) {
                obj['activity'] = ApiClient.convertToType(data['activity'], 'String');
            }
            if (data.hasOwnProperty('log')) {
                obj['log'] = ApiClient.convertToType(data['log'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/TaskStatus} taskStatus
 */
TaskUpdate.prototype['taskStatus'] = undefined;

/**
 * One-liner to indicate what's currently happening with the task. Overwrites previously sent activity strings.
 * @member {String} activity
 */
TaskUpdate.prototype['activity'] = undefined;

/**
 * Log lines for this task, will be appended to logs sent earlier.
 * @member {String} log
 */
TaskUpdate.prototype['log'] = undefined;






export default TaskUpdate;

