/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class WorkerStatus.
* @enum {}
* @readonly
*/
export default class WorkerStatus {
    
        /**
         * value: "starting"
         * @const
         */
        "starting" = "starting";

    
        /**
         * value: "awake"
         * @const
         */
        "awake" = "awake";

    
        /**
         * value: "asleep"
         * @const
         */
        "asleep" = "asleep";

    
        /**
         * value: "error"
         * @const
         */
        "error" = "error";

    
        /**
         * value: "testing"
         * @const
         */
        "testing" = "testing";

    
        /**
         * value: "offline"
         * @const
         */
        "offline" = "offline";

    

    /**
    * Returns a <code>WorkerStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/WorkerStatus} The enum <code>WorkerStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

