/**
 * Flamenco manager
 * Render Farm manager API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkerStatus from './WorkerStatus';

/**
 * The WorkerStatusChangeRequest model module.
 * @module model/WorkerStatusChangeRequest
 * @version 0.0.0
 */
class WorkerStatusChangeRequest {
    /**
     * Constructs a new <code>WorkerStatusChangeRequest</code>.
     * Request for a Worker to change its status to &#x60;status&#x60;.
     * @alias module:model/WorkerStatusChangeRequest
     * @param status {module:model/WorkerStatus} 
     * @param isLazy {Boolean} Whether the status change should happen immediately, or after the worker's current task is finished. 
     */
    constructor(status, isLazy) { 
        
        WorkerStatusChangeRequest.initialize(this, status, isLazy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status, isLazy) { 
        obj['status'] = status;
        obj['is_lazy'] = isLazy;
    }

    /**
     * Constructs a <code>WorkerStatusChangeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkerStatusChangeRequest} obj Optional instance to populate.
     * @return {module:model/WorkerStatusChangeRequest} The populated <code>WorkerStatusChangeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkerStatusChangeRequest();

            if (data.hasOwnProperty('status')) {
                obj['status'] = WorkerStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('is_lazy')) {
                obj['is_lazy'] = ApiClient.convertToType(data['is_lazy'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/WorkerStatus} status
 */
WorkerStatusChangeRequest.prototype['status'] = undefined;

/**
 * Whether the status change should happen immediately, or after the worker's current task is finished. 
 * @member {Boolean} is_lazy
 */
WorkerStatusChangeRequest.prototype['is_lazy'] = undefined;






export default WorkerStatusChangeRequest;

